"use strict";

module.exports = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: [
        "getting-started",
        "overview",
        "components",
        "environments",
        "templates"
      ]
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "loading-kubernetes-yaml",
        "loading-helm-chart",
        "typescript-support",
        "ecmascript-modules",
        "programmatic-usage",
        "troubleshooting"
      ]
    },
    {
      type: "category",
      label: "References",
      collapsed: false,
      items: ["commands", "configuration"]
    }
  ],
  api: [
    "api/modules",
    {
      type: "category",
      label: "Modules",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "api/modules"
        }
      ]
    },
    {
      type: "category",
      label: "Classes",
      items: [
        {
          type: "autogenerated",
          dirName: "api/classes"
        }
      ]
    },
    {
      type: "category",
      label: "Enums",
      items: [
        {
          type: "autogenerated",
          dirName: "api/enums"
        }
      ]
    },
    {
      type: "category",
      label: "Interfaces",
      items: [
        {
          type: "autogenerated",
          dirName: "api/interfaces"
        }
      ]
    }
  ]
};
